Expect jobs to fail

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -40,23 +40,28 @@ jobs:
     outputs:
       matrix: ${{ steps.setup-matrix.outputs.matrix }}
     steps:
-      - uses: druzsan/setup-matrix@feature/use-python-dockerfile
+      - id: expected-to-fail
+        uses: druzsan/setup-matrix@feature/use-python-dockerfile
         continue-on-error: true
+      - if: steps.expected-to-fail.outcome != 'failure'
+        run: echo "Step expected to fail didn't fail" && exit 1
   setup-matrix-windows:
     runs-on: windows-latest
-    outputs:
-      matrix: ${{ steps.setup-matrix.outputs.matrix }}
     steps:
-      - uses: druzsan/setup-matrix@feature/use-python-dockerfile
+      - id: expected-to-fail
+        uses: druzsan/setup-matrix@feature/use-python-dockerfile
         with:
-          matrix: '{ os: [ubuntu-latest, windows-latest] }'
+          matrix: '{ os: [ubuntu-latest, windows-latest], python-version: [3.8, 3.10, 3.12] }'
         continue-on-error: true
+      - if: steps.expected-to-fail.outcome != 'failure'
+        run: echo "Step expected to fail didn't fail" && exit 1
   setup-matrix-macos:
     runs-on: macos-latest
-    outputs:
-      matrix: ${{ steps.setup-matrix.outputs.matrix }}
     steps:
-      - uses: druzsan/setup-matrix@feature/use-python-dockerfile
+      - id: expected-to-fail
+        uses: druzsan/setup-matrix@feature/use-python-dockerfile
         with:
-          matrix: '{ os: [ubuntu-latest, windows-latest] }'
+          matrix: '{ os: [ubuntu-latest, windows-latest], python-version: [3.8, 3.10, 3.12] }'
         continue-on-error: true
+      - if: steps.expected-to-fail.outcome != 'failure'
+        run: echo "Step expected to fail didn't fail" && exit 1
